dirs:
  imagenet: /st1/dataset/learn2sample/imagenet_l2s_84_84
  imagenet_devkit: /v9/whshin/imagenet/ILSVRC2012_devkit_t12
  result: result

ctrl:
  diverse_start: True
  sync_baseline: True
  async_stream: True
  no_valid: False  # for debugging
  no_log: False
  q_track:
    train: True
    test: True

steps:
  outer:
    max: 1000
    anneal: 0  # 0 = no annealing
  inner:
    max: 500
    unroll: 50
    log: 25
    query: 50
  test:
    outer: 5
    inner: 10
    log: 20

loader:
  input_dim: [3, 84, 84]
  class_balanced: False
  split_method: exclusive  # inclusive / exclusive
  class_size: 10
  sample_size: 5
  batch_size: 64
  num_workers: 2
  pin_memory: True

model:
  lr: 0.0001  # metric
  # lr: 0.01  # fc
  optim: sgd
  embed_dim: 256
  channels: [64, 64, 64, 64]
  kernels: [3, 3, 3, 3]
  fc_pulling: False
  distance_type: euclidean  # euclidean / cosine

sampler:
  lr: 0.001
  grad_norm: 40
  rnn_dim: 256
  optim: adam  # adam / rmsprop
  mask_unit: class  # sample / class
  input_more: True
  output_more: True
  temp: 1.0
  eps: 0.1  # epsilon-greedy
  encoder:
    reuse_model: False
    lr: 0.01
    channels: [64, 64]
    kernels: [3, 3]

rl:
  max_action_collapsed: 10
  gamma: 0.99
  gae: False
  tau: 1.00

logs:
  log_steps: 20
  log_mask: True
